### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by fmhess** [nickg/nvc#364] opened 2017-12-29 22:34 UTC
commit f025907b4c22e07a5ba9c9f7b982d812da798ea3
causes the following error for me:

<pre>
nvc -a ../../src/util/gpib_transceiver.vhd ../../src/ieee_488_1_state/interface_function_common.vhd ../../src/ieee_488_1_state/interface_function_AH.vhd ../../src/ieee_488_1_state/interface_function_C.vhd ../../src/ieee_488_1_state/interface_function_DC.vhd ../../src/ieee_488_1_state/interface_function_DT.vhd ../../src/ieee_488_1_state/interface_function_LE.vhd ../../src/ieee_488_1_state/interface_function_PP.vhd ../../src/ieee_488_1_state/interface_function_RL.vhd ../../src/ieee_488_1_state/interface_function_SH.vhd ../../src/ieee_488_1_state/interface_function_SR.vhd ../../src/ieee_488_1_state/interface_function_TE.vhd ../../src/ieee_488_1_state/remote_message_decoder.vhd ../../src/ieee_488_1_state/integrated_interface_functions.vhd ../test_common.vhd integrated_interface_functions_testbench.vhd
nvc -e integrated_interface_functions_testbench
/usr/bin/gcc -shared -o /home/fhess/fmh_gpib_core/testbench/ieee_488_1_state/work/_WORK.INTEGRATED_INTERFACE_FUNCTIONS_TESTBENCH.elab.so /home/fhess/fmh_gpib_core/testbench/ieee_488_1_state/work/_WORK.INTEGRATED_INTERFACE_FUNCTIONS_TESTBENCH.elab.o
nvc -r integrated_interface_functions_testbench --wave
** Note: writing FST waveform data to integrated_interface_functions_testbench.fst
nvc: symbol lookup error: /home/fhess/fmh_gpib_core/testbench/ieee_488_1_state/work/_WORK.INTEGRATED_INTERFACE_FUNCTIONS_TESTBENCH.elab.so: undefined symbol: WORK.INTERFACE_FUNCTION_COMMON.TO_X0Z$LL
Makefile:32: recipe for target 'integrated_interface_functions_testbench.fst' failed
make: *** [integrated_interface_functions_testbench.fst] Error 127
</pre>

**Comment by nickg** [comment] 2017-12-30 16:17
This is caused by packages using a mix of native and JIT compilation. It's fixed now as everything uses native compilation by default. I'll remove the JIT backend eventually as it's actually slower than building a native code shared library in all cases.

**Closed by nickg** 2017-12-30 16:17 UTC
